# Generated by Django 5.2.13 on 2026-04-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='recorded_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
