# Generated by Django 5.2.13 on 2026-04-14 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_lesson_recorded_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='handwritten_notes',
            field=models.FileField(blank=True, null=True, upload_to='handwritten_notes/'),
        ),
    ]
