# Generated by Django 5.2.13 on 2026-04-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0002_employee_leave_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayAnniversary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Birthday', 'Birthday'), ('Anniversary', 'Anniversary')], max_length=20)),
                ('event_date', models.DateField()),
                ('years_completed', models.IntegerField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
