# Generated by Django 5.2.13 on 2026-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_leave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
