# Generated by Django 5.2.13 on 2026-04-26 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_leave_leave_type_alter_leave_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='leave_type',
        ),
        migrations.RemoveField(
            model_name='leave',
            name='to_date',
        ),
        migrations.AddField(
            model_name='leave',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 4, 26)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leave',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 4, 26)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
