# Generated by Django 5.2.13 on 2026-04-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_leave_from_date_remove_leave_leave_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Casual Leave', 'Casual Leave'), ('Paid Leave', 'Paid Leave')], default='Sick Leave', max_length=50),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
